Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "peru/windows-10-enterprise-x64-eval"
  config.vm.box_version = "20220202.01"

  config.vm.provider "libvirt" do |libvirt|
    libvirt.management_network_mode = 'veryisoled'
  end


  config.vm.define :win_victim do |win_victim|
    win_victim.vm.network :private_network,
      :libvirt__network_name => "containers"
  end

  config.vm.box_check_update = false
end
